// Pilot.js - Pilot model

const mongoose = require('mongoose')
const { Schema } = mongoose

const pilotSchema = new Schema({

  ships: [ {
    // fleet with a limit of 10 ships
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Ship'
  } ],

  _owner: { type: Schema.Types.ObjectId, ref: 'Player' },

  personality: String,

  phrases: [
    {
      type: String
    }
  ],

  level: {
    // generated on update, based on single ship stats
    type: Number,
    default: 0
  },

  fleetLevel: {
    // combined fleet power + combat rating level
    type: Number,
    default: 0
  },

  credits: {
    // last updated credits ( not including pending )
    type: Number,
    default: 0
  },

  pendingCredits: {
    // credits to be added or removed
    type: Number,
    default: 0
  },

  faction: {
    // generated by client based on relations
    type: String,
    default: 'Free Worlds'
  },

  world: {
    // for multiple maps
    type: String,
    default: 'alpha'
  }
})

const Pilot = mongoose.model('Pilot', pilotSchema)

module.exports = Pilot
