// Pilot.js - Pilot model

const mongoose = require('mongoose')
const { Schema } = mongoose

const Player = require('models/Player')
const Ship = require('models/Ship')

const pilotSchema = new Schema({

  name: {
    type: String,
    required: true
  },

  ships: [ {
    // fleet with a limit of 10 ships
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Ship'
  } ],

  _owner: { type: Schema.Types.ObjectId, ref: 'Player' },

  personality: String,

  phrases: [
    {
      type: String
    }
  ],

  fleetLevel: {
    // combined fleet power + combat rating level
    type: Number,
    default: 0
  },

  credits: {
    // last updated credits ( not including pending )
    type: Number,
    default: 0
  },

  pendingCredits: {
    // credits to be added or removed
    type: Number,
    default: 0
  },

  faction: {
    // generated by client based on relations
    type: String,
    default: 'Free Worlds'
  }
},
{ // settings
  timestamps: true
})

pilotSchema.pre('remove', async function (next) {
  try {
    // find the owner of the pilot
    const owner = await Player.findById(this._owner)

    // remove id of the pilot from list
    await owner.pilots.remove(this.id)

    // remove ships owned by pilot
    await Ship.deleteMany({ _owner: this._id })

    // save user
    await owner.save()

    return next()
  } catch (error) {
    return next(error)
  }
})

const Pilot = mongoose.model('Pilot', pilotSchema)

module.exports = Pilot
