// Player model

const mongoose = require('mongoose')
const bcrypt = require('bcrypt')

const playerSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true,
    unique: true
  },

  password: {
    type: String,
    required: true,
    minlength: 6
  },

  level: {
    // generated on update, based on single ship stats
    type: Number,
    required: true
  },

  fleetLevel: {
    // combined fleet power + combat rating level
    type: Number,
    required: true
  },

  credits: {
    // last updated credits ( not including pending )
    type: Number,
    required: true
  },

  ships: [{
    // fleet with a limit of 10 ships
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Ship'
  }],

  // stock: [{
  //   // outfits in cargo
  //   name: {
  //     type: String,
  //     required: true
  //   },

  //   amount: {
  //     type: Number,
  //     required: true
  //   }
  // }],

  faction: {
    // generated by client based on relations
    type: String,
    required: true
  },

  world: {
    // for multiple maps
    type: String,
    default: 'alpha'
  },

  pendingCredits: {
    // credits to be added or removed
    type: Number,
    default: 0
  }
})

const Player = mongoose.model('Player', playerSchema)

module.exports = Player
