// Player model

const mongoose = require('mongoose')
const bcrypt = require('bcrypt')

const playerSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true,
    unique: true
  },

  password: {
    type: String,
    required: true,
    minlength: 6
  },

  level: {
    // generated on update, based on single ship stats
    type: Number,
    default: 0
  },

  fleetLevel: {
    // combined fleet power + combat rating level
    type: Number,
    default: 0
  },

  credits: {
    // last updated credits ( not including pending )
    type: Number,
    default: 0
  },

  ships: [ {
    // fleet with a limit of 10 ships
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Ship'
  } ],

  faction: {
    // generated by client based on relations
    type: String,
    default: 'Free Worlds'
  },

  world: {
    // for multiple maps
    type: String,
    default: 'alpha'
  },

  pendingCredits: {
    // credits to be added or removed
    type: Number,
    default: 0
  }
})

playerSchema.pre('save', async function (next) {
  try {
    if (!this.isModified('password')) return next()

    // hash password and save it
    const hashedPassword = await bcrypt.hash(this.password, 10)
    this.password = hashedPassword

    return next()
  } catch (error) {
    return next(error)
  }
})

playerSchema.methods.comparePassword = async function (candidatePassword, next) {
  try {
    const isMatch = await bcrypt.compare(candidatePassword, this.password)

    return isMatch
  } catch (error) {
    return next(error)
  }
}

const Player = mongoose.model('Player', playerSchema)

module.exports = Player
